name: PHP Composer

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [ 7.4, 8.0, 8.1, 8.2, 8.3 ]

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run php-cs-fixer
        run: "./vendor/bin/php-cs-fixer check --config ./.php-cs-fixer.dist.php src/ tests/"

      - name: Run PHPStan
        run: composer run-script phpstan

      - name: Run test suite
        run: composer run-script test
